### ISSUE TITLE
working with formats that aren't .dat? (MultiDoge specifically)

### ISSUE THREAD

**Issue by thisissami** [glv2/bruteforce-wallet#21]
Hello - I'm trying to bruteforce my MultiDoge wallet, which uses it's own .wallet format. I'm assuming this script wouldn't work for that, but figured I should check in here just in case? Any thoughts about this?

**Comment by mtmulch** [comment]
Hey mate perhaps this would provide some insight. If you make your way to the multi-doge repo and take a look through the source, it seems like they use a HashMap of some sort for their wallet and maybe right it to disk? This library seems to only support brute forcing wallets passed off Berkeley DB
https://github.com/langerhans/multidoge/blob/master/src/main/java/com/piuk/blockchain/MyWallet.java

However, since I'm working on getting into my Dogecoin Core wallet, I wanted to try anyways. I installed multidoge gave the wallet a password. And attempted to use this library using the dictionary method with the correct password. Lo and behold I got this error.

```
Error: couldn't open "main" database in "multidoge.wallet": No such file or directory
Error: couldn't find required info in wallet.
```
I want to say this library isn't your best bet.

**Comment by thisissami** [comment]
@mtmulch - hey thanks so much for giving that a try! i appreciate your effort. :) i wish i understood more about the `.wallet` & `.key` files that MultiDoge generates. i could try to write my own script to bruteforce things if I knew which file I had to decrypt using what algorithm. I'll have to look through the MultiDoge source code in a week or so when I've got some time to see if I can figure anything out.

**Comment by mtmulch** [comment]
Personally the file that I tried was located at ~/MultiDoge/multidoge.wallet on Ubuntu after installing Multidoge to the default location. I assumed the .wallet was self explanatory, but I could be totally wrong.

**Comment by thisissami** [comment]
Ah this should work for me (but using the .key file, not the .wallet): https://github.com/gurnec/btcrecover

**Comment by thisissami** [comment]
For anybody needing MultiDoge recovery in the future, use the above link :)

**Comment by pandaloco** [comment]
were you able to get your password? i've been trying forever to get mine no luck would you mine sharing you inputs commands on btcrecover?

**Comment by surge2o** [comment]
It's a scam....  I didn't get anything after paying the fee

**Comment by anywalletrecovery** [comment]
@pandaloco 
@thisissami 
I have machine for wallet recovery and can recover wallet password
Telegram: @walletrecover
