### ISSUE TITLE
What is the reason of low speed of trying? 

### ISSUE THREAD

**Issue by MrBrighty** [glv2/bruteforce-wallet#3]
Hello glv2.

First of all many thanks for this code, which I'm using now to find a password.

Could you share your opinion regarding the reason of speed of password trying. AS for me, now I have 40-passwords per second. If I'll buy better RAM, will I get higher rate?

Or, probably there is other way to  increase the speed rate? 

My computer info:
Intel Core I3-2100 3.10 GHz
RAM 2.00 GB
NVIDIA GeForce GT 630
Windows 7 using virtual box for XUbuntu

Thanks for feedback.

**Comment by glv2** [comment]
Decrypting the master key of the wallet requires a key and an initialisation vector that are derived from the password you enter. This key derivation process is using many iterations of a hash function to be slow on purpose, so that someone who stole a wallet file is unable to find its password quickly.

Usually, the iteration count is chosen during the encryption of the wallet so that the key derivation takes around 1 second (therefore this count depends on the speed of the computer doing the encryption).

Of course decrypting on a faster computer will take less time (if the computer is 10 times faster, the decryption will take 0.1 second instead of 1). Another way to speed things up is to split the work on several computers, running the program with as many threads as processors on each computer.

**Comment by MrBrighty** [comment]
So way you suggest:
1) Split the work on several computers

2) When you're saying "faster computer", what is the core of the speed? Is it RAM? If yes, in case I'll buy better RAM, will i speed up?

**Comment by glv2** [comment]
As the hash function used in the key derivation is sha512, I think the decryption speed depends mainly on the speed of the CPU.
A faster RAM will probably not have a big effect on the decryption speed.

**Comment by Lionsara** [comment]
Hello. is possible to decryption on GPU? i have 10 GPU with 10 GB each..
Thanks

**Comment by glv2** [comment]
Currently decryption using GPUs is not implemented.
